solution
mate-academy/layout_dia pull request #15
Opened 2019-09-04 11:22 UTC by KosBelozyorov

[Demo](https://kosbelozyorov.github.io/layout_dia/)

2019-09-04 11:33 UTC, YuriiHoliuk reviewed
Де HTML файл?

Не вкладай селектори ьуз амперсанда, цим ти збільшуєш специфічність

2019-09-04 11:39 UTC, KosBelozyorov commented
> Де HTML файл?
> 
Усі файли на місці

2019-09-04 11:39 UTC, danheim commented
Фотографии потеряли качество
<img width="1164" alt="Screen Shot 2019-09-04 at 2 35 26 PM" src="https://user-images.githubusercontent.com/36257947/64251467-49c49080-cf21-11e9-818a-2f55d4bd2c54.png">

С этими округленными прямоугольниками похожая ситуация, потеря качества из-за плохого масштабирования
<img width="1437" alt="Screen Shot 2019-09-04 at 2 36 08 PM" src="https://user-images.githubusercontent.com/36257947/64251532-711b5d80-cf21-11e9-9032-ca32160d40db.png">

Плейсхолдер не соответствует позиции начала ввода текста
<img width="210" alt="Screen Shot 2019-09-04 at 2 37 05 PM" src="https://user-images.githubusercontent.com/36257947/64251555-81333d00-cf21-11e9-885c-2dba98729690.png">

Фонтсайз кнопки следует увеличить
<img width="260" alt="Screen Shot 2019-09-04 at 2 37 36 PM" src="https://user-images.githubusercontent.com/36257947/64251581-90b28600-cf21-11e9-8f94-ee5e44dc8bb2.png">

Адаптивность привязана к конкретным числам ширины - это не ок. Блоки должны иметь 90: ширины в мобильных версиях (растягиваться)

2019-09-04 11:44 UTC, danheim requested changes
Работа хорошая, но нужны доработки

2019-09-04 11:44 UTC, danheim commented on src/index.html
> +            </li>
этот закрывающий тег чувствует себя одиноко (перенос некорректный)

2019-09-04 11:44 UTC, danheim commented on src/index.html
> +            class="slide__photo" />
давай переносить уже не один атрибут, а каждый на новый ряд, закрывающий тег тоже

2019-09-04 11:44 UTC, danheim commented on src/index.html
> +            <span>intro</span><br>By the same illusion which lifts the horizon.
все в одну строку - не ок
сделай спан элемент блочным чтобы не нужен был `<br>`

2019-09-04 11:44 UTC, danheim commented on src/index.html
> +      <div class="socials__container">
множественный класс к слово `social` тут не нужен, думаю

2019-09-04 11:44 UTC, danheim commented on src/index.html
> +            class="icon__img"></div>
не понимаю такого переноса, очень странно выглядит + альт пустой

2019-09-04 11:47 UTC, KosBelozyorov commented on src/index.html
> +            class="icon__img"></div>
> не понимаю такого переноса, очень странно выглядит + альт пустой

согласно рекомендаций Гугла, если картинка не несет никакой информации alt можно оставить пустым, я их сейчас по убираю

2019-09-04 11:48 UTC, KosBelozyorov commented on src/index.html
> +      <div class="socials__container">
на social линтер ругается ) а в множественном числе ок..

2019-09-04 15:10 UTC, KosBelozyorov commented on src/index.html
> +            </li>
> этот закрывающий тег чувствует себя одиноко (перенос некорректный)

исправил

2019-09-04 15:10 UTC, KosBelozyorov commented on src/index.html
> +            class="slide__photo" />
исправил

> давай переносить уже не один атрибут, а каждый на новый ряд, закрывающий тег тоже

2019-09-04 15:10 UTC, KosBelozyorov commented on src/index.html
> +            <span>intro</span><br>By the same illusion which lifts the horizon.
> все в одну строку - не ок
> сделай спан элемент блочным чтобы не нужен был `<br>`

исправил

2019-09-04 15:11 UTC, KosBelozyorov commented on src/index.html
> +            class="icon__img"></div>
> не понимаю такого переноса, очень странно выглядит + альт пустой

исправил

2019-09-04 15:13 UTC, KosBelozyorov commented
отступ в input - исправил
размер шрифта у кнопки - исправил

2019-09-04 16:50 UTC, KosBelozyorov commented
поправил адаптивность + исправил логотип в мобильной версии, добавил стили для меню в мобильной версии

2019-09-05 07:14 UTC, KosBelozyorov commented
+ добавил плавный скролинг

2019-09-05 07:27 UTC, danheim commented
Когда будет свободное время:

Ховер эффект на инпуты
<img width="762" alt="Screen Shot 2019-09-05 at 10 26 03 AM" src="https://user-images.githubusercontent.com/36257947/64320661-b1351b80-cfc7-11e9-9a8e-b9ef1d2f49b7.png">

Давай сделаем ховер эффект translateY для иконок
<img width="249" alt="Screen Shot 2019-09-05 at 10 26 43 AM" src="https://user-images.githubusercontent.com/36257947/64320677-b98d5680-cfc7-11e9-8589-d95521160f87.png">

2025-09-21 20:47 UTC, closed without merging