test
mate-academy/layout_dia pull request #265
Opened 2021-09-07 07:13 UTC by Ruslan-Mykhalchak

[DEMO LINK](https://Ruslan-Mykhalchak.github.io/layout_dia/)

2021-09-09 07:53 UTC, OleksiiBlezniuk reviewed
В версии с шириной 1600рх у тебя горизонтальные отступы больше, чем в макете, исправь пожалуйста🙂 
Так же нужно сделать кнопки круглыми
Во втором блоке в макете у текста другой шрифт + он выровнен по центру
В блоке "Our expertise" в карточках у картинок не совсем такой размер, они ведь в макете квадратные 166х166
<img width="243" alt="Снимок экрана 2021-09-09 в 10 47 58" src="https://user-images.githubusercontent.com/84275496/132644923-ce213cbd-95aa-473a-94ce-12520c85e14a.png">
При размере 1024рх  отступ ммежду навигацией и картинкой сильно большой
При размере 768рх тоже нужно подправить, там ещё картинка наезжает на текст
<img width="584" alt="Снимок экрана 2021-09-09 в 10 50 37" src="https://user-images.githubusercontent.com/84275496/132645425-feb4145a-2fcb-4c20-800e-88d7b91959b0.png">
Мобильную версию тоже нужно доработать🙂
<img width="584" alt="Снимок экрана 2021-09-09 в 10 52 57" src="https://user-images.githubusercontent.com/84275496/132645722-2da5674e-859b-4c5a-8d72-7e94f8482663.png">
Продолжай работу 🚀

2021-09-10 16:09 UTC, OleksiiBlezniuk reviewed
Иконка в карточке process не та, числа в этих карточках нужно выровнять
Сделай favicon чёрным
Hover на кнопке не соответствует дизайну
<img width="417" alt="Снимок экрана 2021-09-10 в 19 08 31" src="https://user-images.githubusercontent.com/84275496/132884065-811a5e94-7b63-46d4-818a-d67addfeeae1.png">
Пофикси иконки соц. сетей
У телефона и адреса отсутствует подпись

2021-09-13 11:52 UTC, Ihor-Karpyn requested changes
https://www.loom.com/share/e5be67cce87742e7857fc0a7006007e7

2021-09-13 11:55 UTC, Ruslan-Mykhalchak commented
> https://www.loom.com/share/e5be67cce87742e7857fc0a7006007e7

ок, зараз виправлю)

2021-09-13 13:30 UTC, Anna-Tkachenko approved these changes
Good job!👍 
Еще пару исправлений:
- Сделай поле message в форме тоже обязательным
- Фон для секций Who we are, process, testimonial #F2F6FA, fix it

2024-09-29 08:58 UTC, closed without merging