Dia landing page
mate-academy/layout_dia pull request #296
Opened 2021-11-01 07:40 UTC by lanebx

[DEMO LINK](https://lanebx.github.io/layout_dia/)

2021-11-01 14:31 UTC, volodymyr-soltys97 requested changes
В цілому гарна робота, тільки варто розділити стилі на різні файли, дуже багато рядків коду зараз. Також потрібно додати іконку для сторінки у вкладці. Також чомусь не відкривається меню на мобільній версії і немає кнопки відкриття, + переключатель для слайдеру позиціонується трохи не там де потрібно у мобільній версії, ось скрін 
![image](https://user-images.githubusercontent.com/64750958/139688242-e29738b0-2fd0-4611-ba52-177c4b488deb.png)

2021-11-01 14:31 UTC, volodymyr-soltys97 commented on src/index.html
> +            </li>
Пам'ятай про стиль написання коду, перевір це по всій сторінці
```suggestion
            <li class="header__item">
              <a href="#about-us" class="header__link">
                About us
              </a>
            </li>
```

2021-11-01 14:31 UTC, volodymyr-soltys97 commented on src/index.html
> +              We strive to create communications that can increase media performance. We use everything — words, meanings, stories, art, movies.            </div>
```suggestion
            <div class="expertise__text">
              We strive to create communications that can increase media performance. We use everything — words, meanings, stories, art, movies. 
            </div>
```

2021-11-01 14:31 UTC, volodymyr-soltys97 commented on src/index.html
> +    <div class="services" id="ervices">
Можливо id="services"?

2021-11-01 14:31 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +    background: #2060F6;
background-color можливо?

2021-11-01 14:31 UTC, volodymyr-soltys97 commented on src/styles/main.scss
> +    color: #FFFFFF;
Я думаю варто створити змінні для кольорів які ти використовуєш більше одного разу

2021-11-02 11:22 UTC, lanebx commented on src/index.html
> +    <div class="services" id="ervices">
corrected

2021-11-02 11:22 UTC, lanebx commented on src/styles/main.scss
> +    background: #2060F6;
corrected

2021-11-02 14:17 UTC, aionova requested changes
<img width="145" alt="Screenshot 2021-11-02 at 16 11 51" src="https://user-images.githubusercontent.com/68023426/139863851-edc7c3e8-86b6-4618-adde-114d49d1d7c6.png">

- hire us should be a clickable link.
- all the buttons and clickable elements should have hover-effect, transition and cursor: pointer
- all buttons should do something, lead you to another part of the website.
- on small screens I see some weird white thing)
<img width="213" alt="Screenshot 2021-11-02 at 16 16 16" src="https://user-images.githubusercontent.com/68023426/139864647-6c8d4d29-4582-4e5a-a14e-23483f7b07b5.png">
Keep working!)

2021-11-04 10:00 UTC, ihor-jpeg requested changes
Good stuff! 🔥  There are a few things to continue working on

- these buttons should have `cursor: pointer` and, optionally, some hover effects
<img width="518" alt="Screenshot 2021-11-04 at 11 45 37" src="https://user-images.githubusercontent.com/79282749/140293105-92e8dc6d-a602-4de1-a4c7-bc6bcf8646f3.png">

- add hover effects to links
<img width="608" alt="Screenshot 2021-11-04 at 11 45 45" src="https://user-images.githubusercontent.com/79282749/140293178-e54c65af-7487-4597-806f-55198a716dc5.png">
<img width="442" alt="Screenshot 2021-11-04 at 11 46 50" src="https://user-images.githubusercontent.com/79282749/140293210-7a0cb4e2-7357-4bae-b6a7-a0170c1d390d.png">

- it might be just me, but letter-spacing here is a bit too much
<img width="206" alt="Screenshot 2021-11-04 at 11 46 31" src="https://user-images.githubusercontent.com/79282749/140294053-b640177b-55d5-48a5-bc3e-3735bd84790f.png">

- the button has a strange border, which disappears on hover
<img width="377" alt="Screenshot 2021-11-04 at 11 47 00" src="https://user-images.githubusercontent.com/79282749/140294236-921ec3a7-aa45-4bca-a8a1-51ab57505199.png">

- and lastly, here is a challenge: can you spot the similarities between these two images? 😆 
<img width="246" alt="Screenshot 2021-11-04 at 11 46 53" src="https://user-images.githubusercontent.com/79282749/140294474-c995fadd-e925-42fc-a890-7e92581ce6ec.png">
<img width="520" alt="Screenshot 2021-11-04 at 11 55 49" src="https://user-images.githubusercontent.com/79282749/140294493-009fec88-9925-4292-86a0-a1660887ffcb.png">

2021-11-04 16:02 UTC, ihor-jpeg requested changes
Your work gets better and better!

- the menu is open by default, but it should not be
<img width="493" alt="Screenshot 2021-11-04 at 17 52 05" src="https://user-images.githubusercontent.com/79282749/140374274-36a4039d-1400-4c0f-bbdb-f3ff0fd2917f.png">
<img width="525" alt="Screenshot 2021-11-04 at 17 52 12" src="https://user-images.githubusercontent.com/79282749/140374322-e57f1f24-55d1-4df2-b682-d3ed6453865a.png">

- there is transition duration on header links, but none on button hover
<img width="282" alt="Screenshot 2021-11-04 at 17 52 27" src="https://user-images.githubusercontent.com/79282749/140374449-5fd49144-5720-4676-a6a2-c9d8728f6fb7.png">

- when i click on the button, the background changes to while
<img width="455" alt="Screenshot 2021-11-04 at 17 52 22" src="https://user-images.githubusercontent.com/79282749/140374557-32619e2a-0af7-488e-b97f-2fe60504e65d.png">

- in some cases 100vh will throw off the layout, for example if a user has a tall screen (this is just my opinion and it's up to you)
<img width="515" alt="Screenshot 2021-11-04 at 17 54 00" src="https://user-images.githubusercontent.com/79282749/140374823-ef4f4f39-f083-44d4-8142-6e2bfdde6263.png">

2021-11-08 19:00 UTC, AlinaMatuschak requested changes
Nice work. But we can better 💪

- Can you render mobile menu on all viewport width&height?
<img width="451" alt="Screenshot 2021-11-08 at 20 54 55" src="https://user-images.githubusercontent.com/47606379/140800949-0fb820a3-eb8a-4f32-a26b-0d86efd95225.png">
- on click"learn more" and "apply" buttons you can lead to the contact block
- small space after button
<img width="722" alt="Screenshot 2021-11-08 at 20 58 46" src="https://user-images.githubusercontent.com/47606379/140801441-d90e6507-867e-411d-8e42-7a2a23d38329.png">
- add hover for these blocks
<img width="597" alt="Screenshot 2021-11-08 at 20 59 36" src="https://user-images.githubusercontent.com/47606379/140801543-cc0f98c2-60a6-425e-b5a9-512bdfb06284.png">

2021-11-09 12:26 UTC, AlinaMatuschak requested changes
- fix autocomplete
![Screenshot 2021-11-09 at 12 52 31](https://user-images.githubusercontent.com/47606379/140911232-99e43b43-5350-4cf0-9b0c-0319477892a8.png)
 
- hover for logo
- on click learn more lead to services block
- on click apply lead to form block
- bug with footer
<img width="1083" alt="Screenshot 2021-11-09 at 14 25 59" src="https://user-images.githubusercontent.com/47606379/140924004-f291f115-a309-4740-b9f4-701469a49006.png">

2021-11-10 09:29 UTC, AlinaMatuschak requested changes
Are you sure that you redeployed?

2021-11-11 09:39 UTC, lanebx commented
> Are you sure that you redeployed?

you're right,
already deployed

2021-11-11 10:35 UTC, aionova requested changes
- these Learn more buttons should also do something
<img width="283" alt="Screenshot 2021-11-11 at 12 17 35" src="https://user-images.githubusercontent.com/68023426/141280912-cb6604eb-00f4-40e8-84aa-da75e0e978d4.png">
- this button should lead you to the form
<img width="445" alt="Screenshot 2021-11-11 at 12 18 38" src="https://user-images.githubusercontent.com/68023426/141281042-3c5d99cd-1486-4880-9625-a3b0e9bb6cb4.png">
 - when I use autocomplete, the input doesn't look good
<img width="552" alt="Screenshot 2021-11-11 at 12 19 11" src="https://user-images.githubusercontent.com/68023426/141281132-8380475e-d113-4e26-8eb4-d52a51262188.png">
- Location of burger-menu icon is not obvious at all. It should be in the right corner
<img width="453" alt="Screenshot 2021-11-11 at 12 21 50" src="https://user-images.githubusercontent.com/68023426/141281498-42b3d70b-8779-4101-85f1-9f585844ec97.png">
- burger-menu should close when you press on one of the items in the menu
- you can add "close" button to the menu.
- make the block paddings and margins smaller on small screens
<img width="468" alt="Screenshot 2021-11-11 at 12 33 21" src="https://user-images.githubusercontent.com/68023426/141283155-ee992b5e-cfd7-4e26-a240-57f0f8d6b34b.png">

2021-11-12 07:54 UTC, aionova approved these changes
GJ!

2021-12-13 12:00 UTC, closed without merging