Create web page DIA
mate-academy/layout_dia pull request #373
Opened 2022-03-12 16:22 UTC by ivan-kadykalo

[DEMO LINK](https://ivan-kadykalo.github.io/layout_dia/)

2022-03-14 20:50 UTC, MaksimusCRS requested changes
Отличная работа! Нужно пару мелких исправлений.

Поля после автозаполнения выглядят поломаными 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/92159085/158257644-6481beb7-5e78-4e98-85b7-5e2a23d3c308.png">

Мобильное меню выглядит поломанным 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/92159085/158258042-7dd5e7f1-6cae-41bd-aac3-69712b446971.png">

2022-03-15 07:27 UTC, ivan-kadykalo commented
> Отличная работа! Нужно пару мелких исправлений.
> 
> Поля после автозаполнения выглядят поломаными <img alt="image" width="514" src="https://user-images.githubusercontent.com/92159085/158257644-6481beb7-5e78-4e98-85b7-5e2a23d3c308.png">
> 
> Мобильное меню выглядит поломанным <img alt="image" width="603" src="https://user-images.githubusercontent.com/92159085/158258042-7dd5e7f1-6cae-41bd-aac3-69712b446971.png">

Уточни будь ласка що саме мені потрібно виправити?
Стосовно форми автозаповнення я піднімав цю тему в Q&A. Маю для неї інші вирішення, зараз внесу поправки якщо це критично.
Для випадаючого меню немає макету, скажи будь ласка що саме виглядає не так, щоб я знав що міняти. 
На перший погляд думаю варто збільшити шрифт пунктів меню в режимі планшета. Цього буде достатньо чи ще щось?

2022-03-15 07:46 UTC, MaksimusCRS commented
> > Отличная работа! Нужно пару мелких исправлений.
> > Поля после автозаполнения выглядят поломаными
> > Мобильное меню выглядит поломанным
> 
> Уточни будь ласка що саме мені потрібно виправити? Стосовно форми автозаповнення я піднімав цю тему в Q&A. Маю для неї інші вирішення, зараз внесу поправки якщо це критично. Для випадаючого меню немає макету, скажи будь ласка що саме виглядає не так, щоб я знав що міняти. На перший погляд думаю варто збільшити шрифт пунктів меню в режимі планшета. Цього буде достатньо чи ще щось?

Да, к сожалению, нет макета меню для этого лендинга, но если смотреть со стороны пользователя, то бросаются в глаза такие пункты:

1. Очень маленький шрифт для такого разрешения
2. Кнопочка Hire Us находится отдельно от остальных, если так задумано - то я бы сделал её размером как Dia
А вообще есть смысл её показывать под всеми кнопками и сделать меню похожим на miami)

Эта работа будет идти тебе в портфолио и её будут смотреть рекрутеры без технических навыков, соответственно они будут смотреть, на внешний вид, учти это :)

2022-03-15 07:56 UTC, ivan-kadykalo commented
Зараз внесу ці поправки. Дякую.

2022-03-18 08:09 UTC, AlinaMatuschak requested changes
- Links in the header should lead to the corresponding blocks of the landing page
<img width="778" alt="Screenshot 2022-03-18 at 09 44 05" src="https://user-images.githubusercontent.com/47606379/158958144-f878c42e-a8de-47a7-8e95-9040dbdeab4f.png">

- "learn more" should lead to "Who we are" block
<img width="298" alt="Screenshot 2022-03-18 at 09 45 18" src="https://user-images.githubusercontent.com/47606379/158958327-131b1ec3-60d3-446b-a5d6-13bbeb7cc58d.png">

- add social links on footer (open on new tab)
<img width="249" alt="Screenshot 2022-03-18 at 10 09 20" src="https://user-images.githubusercontent.com/47606379/158961523-1311ceaa-9978-4ff7-9253-df49fae835da.png">

2022-03-22 10:34 UTC, MaksimusCRS approved these changes
Well Done!

2023-08-08 17:43 UTC, closed without merging