solution
mate-academy/layout_dia pull request #434
Opened 2022-07-07 14:12 UTC by Dmytro-Kretov

https://Dmytro-Kretov.github.io/layout_dia/

2022-07-09 08:32 UTC, marina-tilniak requested changes
варто використовувати ті кольори які вже є у дизайні
<img width="800" alt="image" src="https://user-images.githubusercontent.com/94261494/178097826-a10cd260-6031-49d7-8714-c458a0eb6fda.png">

варто змінити дефолтні стилі при автокомпліті [(читай тут)](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/)
<img width="438" alt="image" src="https://user-images.githubusercontent.com/94261494/178097871-3ca48e40-9805-4bf6-a38d-1f39f37e3c0f.png">

відправка форми не повинна перезавантажувати сторінку

зовнішні посилання  мають відкриватися у новій вкладці
<img width="270" alt="image" src="https://user-images.githubusercontent.com/94261494/178097935-bdd2ac3a-b7cd-4a14-8994-056f62ead042.png">

лінк у лого переходить на 404
<img width="350" alt="image" src="https://user-images.githubusercontent.com/94261494/178097964-23d03441-7a80-4a5b-bb6b-4ab6c6dc8d94.png">

на посилання варто додати hover effects

2022-07-11 10:13 UTC, Dmytro-Kretov commented
> варто використовувати ті кольори які вже є у дизайні - DONE
> варто змінити дефолтні стилі при автокомпліті [(читай тут)](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/) <img alt="image" width="438" src="https://user-images.githubusercontent.com/94261494/178097871-3ca48e40-9805-4bf6-a38d-1f39f37e3c0f.png">

хотів би уточнити, що саме замінити? 
<img width="373" alt="Знімок екрана 2022-07-11 о 13 10 26" src="https://user-images.githubusercontent.com/105914602/178242208-13b31848-4fc9-4f1b-afb6-95e53eb1cf60.png">

> 
> відправка форми не повинна перезавантажувати сторінку - DONE
> 
> зовнішні посилання мають відкриватися у новій вкладці <img alt="image" width="270" src="https://user-images.githubusercontent.com/94261494/178097935-bdd2ac3a-b7cd-4a14-8994-056f62ead042.png"> - DONE
> 
> лінк у лого переходить на 404 <img alt="image" width="350" src="https://user-images.githubusercontent.com/94261494/178097964-23d03441-7a80-4a5b-bb6b-4ab6c6dc8d94.png"> - DONE
> 
> на посилання варто додати hover effects - DONE

2022-07-13 13:13 UTC, Bohdan-Maksymiuk commented
> хотів би уточнити, що саме замінити?

заливку дефолтну

2022-07-15 11:59 UTC, Dmytro-Kretov commented
в розмірі 320 кнопка посерелині знахожитьс
<img width="488" alt="Знімок екрана 2022-07-15 о 14 58 23" src="https://user-images.githubusercontent.com/105914602/179218804-f9733912-d096-4211-8127-2f34f31df2f5.png">
я

2022-07-19 11:22 UTC, ArturErmolenko approved these changes

2023-10-12 12:00 UTC, closed without merging