Dia landing
mate-academy/layout_dia pull request #600
Opened 2023-03-05 15:00 UTC by NazikVr

[DEMO LINK](https://NazikVr.github.io/layout_dia/).

2023-03-06 08:59 UTC, polosanya requested changes
1. Check how your page looks on large screens using DevTools
![image](https://user-images.githubusercontent.com/96409563/223062804-1c534744-9f03-4c18-87b0-293dffb4c30d.png)
2. Let's add a favicon for the page
![image](https://user-images.githubusercontent.com/96409563/223062893-a11c3132-da79-4ce6-81e5-8865eeac22ac.png)
3. Add hover effects to images
![image](https://user-images.githubusercontent.com/96409563/223062969-44f039d1-0ed6-495a-9695-18be5597953c.png)
4. Same with these cards and links
![image](https://user-images.githubusercontent.com/96409563/223063048-24dcfe44-b334-4f6d-ba23-c5048128457c.png)
![image](https://user-images.githubusercontent.com/96409563/223063084-0b5f2288-5210-4a90-a3ac-69bd7e5eee04.png)
5. Make sure that all the buttons are active and have cursor pointer on hover
![image](https://user-images.githubusercontent.com/96409563/223063220-6cae283f-b9dd-4557-a325-080c46908d7f.png)
6.  After autocomplete the form, change the [default styles](http://joxi.ru/EA4xgG8HXwL4lA). Read more about [changing autocomplete styles](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/)
![image](https://user-images.githubusercontent.com/96409563/223063391-556005e7-092c-44fa-8483-8c09323aa724.png)

2023-03-08 08:42 UTC, OlEzhA0 requested changes
please check required fields
https://user-images.githubusercontent.com/60295799/223664322-1bb98eeb-fb8d-4542-b183-7c5ed239404e.mov

menu not opening

2023-03-09 08:53 UTC, polosanya requested changes
1. Favicon is a bit streched 
![image](https://user-images.githubusercontent.com/96409563/223967114-1ca838ed-a096-47d6-84fb-6f24d46f00b2.png)
2. Make sure that all buttons do something (e.g. navigate to some section)
![image](https://user-images.githubusercontent.com/96409563/223969019-fd80a7a8-805a-4b7a-b99f-9083e1ef7a44.png)
3. The font of links doesn't match the design
![image](https://user-images.githubusercontent.com/96409563/223969185-6aaee6a2-7b75-4262-84f3-44f0697e3012.png)
![image](https://user-images.githubusercontent.com/96409563/223969217-5a83f6f0-076e-4c44-9ff4-ebc6c063d049.png)
4. I think it's better to reduce the gap between links in burger menu
![image](https://user-images.githubusercontent.com/96409563/223970236-8d0ce829-741b-4c8f-b943-987867da05ef.png)

2023-03-10 07:52 UTC, OleziO requested changes
Fixing picture sizes and making the change of pictures in the carousel is not so frequent.
![image](https://user-images.githubusercontent.com/56752562/224254238-b8cfb822-4be9-43e8-a9be-0bcac577b1c8.png)

Design:
![image](https://user-images.githubusercontent.com/56752562/224254657-bae87eb5-80aa-4460-bb12-1f74e3fe5ec2.png)
Demo:
![image](https://user-images.githubusercontent.com/56752562/224254770-074fe28c-ce9c-4de2-8558-4d3decd552bb.png)

![image](https://user-images.githubusercontent.com/56752562/224255014-204321bb-7535-4e55-a28e-fcd7acfbb9db.png)
You need to use word `tel:` to make your link as a phone number, like this: `<a href="tel:+496170961709"  />`

![image](https://user-images.githubusercontent.com/56752562/224255736-fef706b0-81c2-4e4e-97bc-e19520848a6d.png)
Use SVG icons to avoid picture quality deterioration.

![image](https://user-images.githubusercontent.com/56752562/224255997-9eef9279-b796-4807-b9e6-6aa14340fd03.png)

If you have any questions - feel free to ask them in `fe_chat`

2025-10-08 16:40 UTC, closed without merging