dia commit
mate-academy/layout_dia pull request #629
Opened 2023-04-05 14:23 UTC by Faridun92

2023-04-05 17:24 UTC, etojeDenys requested changes
you forgot to add the demo link

2023-04-06 07:31 UTC, DarkMistyRoom requested changes
Good job! Fix some comments:
- make the logo a link to a header section
![image](https://user-images.githubusercontent.com/98764641/230304206-4ff67ea6-5b25-4002-b925-243fba71eb11.png)

- add some hover effects to all images, links, and buttons

- round these angles
![image](https://user-images.githubusercontent.com/98764641/230305100-555fe6fd-89ac-44d7-adcc-5f92526801bd.png)

- fix the menu and remove the page scroll
![image](https://user-images.githubusercontent.com/98764641/230305341-96fd2446-9387-46ea-b23a-33fe08597e84.png)

- fix this section
![image](https://user-images.githubusercontent.com/98764641/230305591-da155882-d31b-4cbc-b1eb-d7b1b9f3651d.png)
figma:
![image](https://user-images.githubusercontent.com/98764641/230305678-88875555-a3fe-45e6-858c-9333cd8419d7.png)

- something went wrong on the mobile
![image](https://user-images.githubusercontent.com/98764641/230305829-d9b0559c-e47b-4772-9b58-e97c7f881b0a.png)

2023-04-06 12:19 UTC, SerhiiKirik requested changes
Great 🔥 
Let's make some improvements 🧑‍💻 
https://www.loom.com/share/071f0346043b4f0a8080141102d7f0b7

2023-04-06 16:00 UTC, loralevitska requested changes
Almost done) Let's improve
- fix hover effect in menu 
![image](https://user-images.githubusercontent.com/70009205/230433086-d232b987-72e7-4c19-8010-1efd519e3611.png)
- best practice - the close menu icon should be on the same level as the burger menu icon
![image](https://user-images.githubusercontent.com/70009205/230433403-da015f72-865c-4bf1-b70e-0cd9350b496d.png)
Please fix it
- add more padding for the burger menu icon for a more comfortable clickable area

2023-04-06 16:42 UTC, etojeDenys requested changes
check-in checklist where you need to add hover effects

2023-04-06 18:35 UTC, polosanya requested changes
Looks really great! Just found a few moments that would be great to fix
1. Remove default underline of the link
![image](https://user-images.githubusercontent.com/96409563/230460563-ac610c99-9db5-44fb-bb02-deee8fa659cb.png)
2. After autocomplete the form, change the [default styles](http://joxi.ru/EA4xgG8HXwL4lA). Read more about [changing autocomplete styles](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/)
![image](https://user-images.githubusercontent.com/96409563/230462607-25e39d17-188e-4b5c-ac8e-fba8c5b6595a.png)
3. Footer doesn't match the design
![image](https://user-images.githubusercontent.com/96409563/230463075-832304bd-4b7f-4ac6-aa50-0b17a21894e0.png)
![image](https://user-images.githubusercontent.com/96409563/230463093-ca3b4131-e272-459f-83b4-d60fb7b1ef03.png)
4. Let's make burger menu a bit prettier. Move cross icon to the top right center and make link bigger
![image](https://user-images.githubusercontent.com/96409563/230465490-60985662-6061-4d9e-994a-e61eb5006e13.png)

2023-04-07 06:25 UTC, SerhiiKirik requested changes
Well done 🚀 
Still not fixed

<img width="329" alt="image" src="https://user-images.githubusercontent.com/91411692/230553539-e248acc9-f4fd-4ec8-9a27-a4fcbbf1fa4b.png">

Also, remove hover effects from Mobile & Tablet
<img width="582" alt="image" src="https://user-images.githubusercontent.com/91411692/230553632-3de95ffa-bc32-4e5a-8e6c-da39425833bd.png">

remove underline from the text
<img width="394" alt="image" src="https://user-images.githubusercontent.com/91411692/230553684-ba078b90-92c4-4156-b3ac-85f9a7a4bbb6.png">

Something is wrong with menu on horizontal tablet
<img width="914" alt="image" src="https://user-images.githubusercontent.com/91411692/230553835-926ff61e-7d30-4bb9-a2f0-c1dc858ac9de.png">

2023-04-07 08:16 UTC, SerhiiKirik requested changes
GJ 🔥 
Let's fix a DEMO link, make a deploy
![image](https://user-images.githubusercontent.com/91411692/230571008-9060f5e1-2959-4023-8de5-171bf83ddf0b.png)

2023-04-07 08:19 UTC, SerhiiKirik requested changes
Good job 🔥 
Let's make some improvements 🧑‍💻 

make a less scale, bc card on the card - it's not ok
![image](https://user-images.githubusercontent.com/91411692/230571258-f122d5e7-bb59-48cf-b0a8-110650e2cda9.png)

Let's put your open menu button & close menu button position on the same position
![image](https://user-images.githubusercontent.com/91411692/230571393-6a3a5957-fbe4-40d3-9f75-8a280cc42502.png)

Also, if i open menu in Ipad air & make a horizontal screen - i can't close menu
![image](https://user-images.githubusercontent.com/91411692/230571484-ae426b05-9668-428a-90f1-90e8758e6e44.png)

2023-04-07 10:17 UTC, vlad-demchuk requested changes
1. decrease scale, it overlaps title
<img width="486" alt="image" src="https://user-images.githubusercontent.com/102411130/230591526-f685d0fb-5c4c-4fc3-8ea5-290f913f5cf9.png">

2023-04-07 10:28 UTC, vlad-demchuk approved these changes

2023-06-02 16:52 UTC, marina-tilniak approved these changes

2026-08-18 22:30 UTC, closed without merging